config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :surveys do
    get '/results' => 'surveys#results'
    resources :answers
    resources :questions
  end

  resources :questions do
    resources :answers
  end

  get '/survey-object' => 'surveys#object'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create', as: 'create_session'
  delete '/logout' => 'sessions#destroy', as: 'logout'
  get 'logout' => 'sessions#destroy'

  root 'welcome#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  has_many :survey_answers
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
  belongs_to :survey

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions
  has_many :survey_answers
  belongs_to :creator, class_name: "User"
end

app/models/survey_answer.rb
class SurveyAnswer < ActiveRecord::Base
  belongs_to :survey
  belongs_to :answer
  belongs_to :user


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true, uniqueness:true
  validates :password, presence: true
  has_many :surveys, foreign_key: :creator_id
  has_many :survey_answers
  has_many :questions, through: :surveys

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @survey = Survey.last
    @question = Question.last

    # render :json => { :id => @survey.id }

  end

  def create
    user_input = params[:answer]
    survey_id = Question.find_by(id: params[:question_id]).survey_id
    user_input.each do |k, v|
      answer = Answer.new(body: v, question_id: params[:question_id])
      if !(answer.save && v.length >= 1)
        flash[:notice] = "problem"
        redirect_to :back
        return
      end
    end
    flash[:notice] = "submit"
    redirect_to new_survey_question_path(survey_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @survey = Survey.find_by(id: params[:survey_id])
    @question = Question.new
  end

  def create
    @question = Question.new(body: params[:question][:body], survey_id: params[:survey_id])
    if @question.save

      render :json => { :id => @question.id }

    else
      flash[:notice] = "you must enter a body"
      redirect_to new_survey_question_path(params[:survey_id])
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if User.find_by(name: user_params[:name]) == nil
      flash[:notice] = "Invalid Username or Password"
      redirect_to login_path
    else
      user = User.find_by(name: user_params[:name])
      user.password == params[:password]
      session[:user_id] = user.id
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :password)
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def results
    @survey = Survey.find_by(params[:id])
    @questions = Survey.find_by(params[:id]).questions
  end

  def index
    @surveys = Survey.all
  end

  def new
    @survey = Survey.new
  end

  def create
    secret_url = SecureRandom.hex(4)
    @survey = Survey.new(name: params[:survey][:name], creator_id: session[:user_id], url: secret_url)
    if @survey.save
      # @id = @survey.id.to_json
      render :json => { :id => @survey.id }
      # render :text => @id.to_json
      # redirect_to new_survey_question_path(@survey.id)
    else
      flash[:notice] = "you must enter a title"
      redirect_to :back
    end
  end

  def object
    session[:survey_id]
  end



  def show
    @survey = Survey.find_by(id: params[:id])
    @questions = @survey.questions
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Account successfully created"
      redirect_to root_path
    else
      flash[:notice] = "User already exists"
      redirect_to login_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    if @user.save
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new()
  end


  def user_params
    params.require(:user).permit(:name,:email,:password)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Account has been deleted"
    redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    !!session[:user_id]
  end

  def answer_count(answer)
    answer.survey_answers.count
  end
end

app/views/answers/new.html.erb
<div class = "create-answers">
<h1>This Form is to fill out the answers to a question</h1>
<%= form_tag("/questions/#{@question.id}/answers", method: :post) do %>
  <%= label_tag "Choice 1: " %>
  <%= text_field_tag "answer[answer1]" %> <br> <br>
  <%= label_tag "Choice 2: " %>
  <%= text_field_tag "answer[answer2]"%> <br> <br>
  <%= label_tag "Choice 3: " %>
  <%= text_field_tag "answer[answer3]" %> <br> <br>
  <%= label_tag "Choice 4: " %>
  <%= text_field_tag "answer[answer4]" %> <br> <br>
  <%= hidden_field_tag 'survey_id', @survey.id %>
  <%= submit_tag "work" %>
<% end %>
<br>
</div>
<% if flash[:notice] == "problem" %>
  <p>You must fill out all forms.</p>
<% end %>
<br>

app/views/layouts/_header.html.erb
<h1> WELCOME TO BUTTER SURVEYS </h1>

  <% if logged_in?  %>
  <%= link_to "#{User.find(session[:user_id]).name}", user_path(session[:user_id]) %>
      <%= link_to 'logout', logout_path, method: :delete %>
    <% else %>
      <%= link_to 'login', login_path %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ButterSurvey</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/new.html.erb
<% if flash[:notice] %>
  <p>Click <%= link_to "here" , @survey %> to submit your survey</p>
<% end %>
<br>


  <%= form_for @question, url: survey_questions_path(@survey.id), method: :post do |f| %>
    <%= f.label :Question %>
    <%= f.text_field :body %>
    <%= hidden_field_tag 'survey_id', @survey.id %>
    <%= f.submit "Create Question" %>
  <% end %>

app/views/surveys/index.html.erb
<h1>Index Page for surveys</h1>

<% @surveys.each do |s| %>
  <%= s.name %> <br>
  <%= s.url %> <br>
<% end %>
<br><br>
<% if session[:user_id] %>
  <%= link_to "Make a new survey", new_survey_path%>
  <%= link_to "Update your survey" %>

<% end %>

app/views/surveys/new.html.erb
<div class="create-survey">
<h1> Make a title for you survey:</h1>
  <%= form_for @survey do |f| %>
    <%= f.label :title %>
    <%= f.text_field :name %>
    <%= f.submit "Create Survey" %>
  <% end %>
</div>

<div class= "create-questions">
<h1> Now add questions:</h1>
</div>

<div class= "create-options">
<h1> Now add answers:</h1>
<div class = "innerfirst"></div>
</div>

<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

app/views/surveys/results.html.erb
<h2><%= @survey.name %></h2>

<% @questions.each do |question| %>
  <h3><%= question.body %></h3>
  <% question.answers.each do |answer| %>
    <li><%= answer.body %>:  <%= answer_count(answer) %></li>
  <% end %>
<% end %>

app/views/surveys/show.html.erb
<h1>Survey <%= @survey.name %></h1>

<% @questions.each do |question| %>
    <% question.answers.each do |answer| %>
      <%= question.body %> <br> <br>
      <%= answer.body %> <br>
  <% end %>
<% end %>

app/views/users/_new.html.erb
<div id="create-account-button">
  <h2>Create Account</h2>
</div>
<div id="create-account-form">
  <%=form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %> <br>
    <%= f.label :email %>
    <%= f.text_field :email %> <br>
    <%= f.label :password %>
    <%= f.password_field :password %> <br>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'layouts/header' %>

<h1>Manage Your Account</h1>

<%=form_for :user, url: user_path(@user), method:  :patch do|f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br>
  <%= f.label :email %>
  <%= f.text_field :email %> <br>
  <%= f.label :password %>
  <%= f.password_field :password %> <br>
  <%= f.submit %>

  <% end %>

  <%= link_to 'Delete My Account', user_path(@user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

app/views/users/index.html.erb
<%= render 'layouts/header' %>

app/views/users/show.html.erb
<%= render 'layouts/header' %>

<h2> My Account </h2>

Name: <%= @user.name %><br>
Email: <%= @user.email %><br>

  <% if @user.id == session[:user_id]%>
    <%= link_to "Manage Your Account", edit_user_path(@user) %>
  <% end %>

<h3> Surveys I Created</h3>

<% @user.surveys.each do |item| %>
<%= link_to "#{item.name}",item %>
<% end %>

app/views/welcome/index.html.erb
<%= render 'layouts/header' %>

  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>